// Do not edit this file; automatically generated by build.py.
'use strict';


// Copyright 2012 Google Inc.  Apache License 2.0
Blockly.PNP=new Blockly.Generator("PNP");Blockly.PNP.addReservedWords("and,as,assert,break,class,continue,def,del,elif,else,except,exec,finally,for,from,global,if,import,in,is,lambda,not,or,pass,print,raise,return,try,while,with,yield,True,False,None,NotImplemented,Ellipsis,__debug__,quit,exit,copyright,license,credits,abs,divmod,input,open,staticmethod,all,enumerate,int,ord,str,any,eval,isinstance,pow,sum,basestring,execfile,issubclass,print,super,bin,file,iter,property,tuple,bool,filter,len,range,type,bytearray,float,list,raw_input,unichr,callable,format,locals,reduce,unicode,chr,frozenset,long,reload,vars,classmethod,getattr,map,repr,xrange,cmp,globals,max,reversed,zip,compile,hasattr,memoryview,round,__import__,complex,hash,min,set,apply,delattr,help,next,setattr,buffer,dict,hex,object,slice,coerce,dir,id,oct,sorted,intern");
Blockly.PNP.init=function(a){};Blockly.PNP.finish=function(a){return a};Blockly.PNP.scrubNakedValue=function(a){return a+"\n"};Blockly.PNP.scrub_=function(a,b){var c=a.nextConnection&&a.nextConnection.targetBlock(),c=Blockly.PNP.blockToCode(c);return b+c};Blockly.PNP.quote_=function(a){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\\n").replace(/\%/g,"\\%").replace(/'/g,"\\'");return""+a+""};Blockly.PNP.ORDER_ATOMIC=0;Blockly.PNP.ORDER_COLLECTION=1;Blockly.PNP.ORDER_STRING_CONVERSION=1;
Blockly.PNP.ORDER_MEMBER=2;Blockly.PNP.ORDER_FUNCTION_CALL=2;Blockly.PNP.ORDER_EXPONENTIATION=3;Blockly.PNP.ORDER_UNARY_SIGN=4;Blockly.PNP.ORDER_BITWISE_NOT=4;Blockly.PNP.ORDER_MULTIPLICATIVE=5;Blockly.PNP.ORDER_ADDITIVE=6;Blockly.PNP.ORDER_BITWISE_SHIFT=7;Blockly.PNP.ORDER_BITWISE_AND=8;Blockly.PNP.ORDER_BITWISE_XOR=9;Blockly.PNP.ORDER_BITWISE_OR=10;Blockly.PNP.ORDER_RELATIONAL=11;Blockly.PNP.ORDER_LOGICAL_NOT=12;Blockly.PNP.ORDER_LOGICAL_AND=13;Blockly.PNP.ORDER_LOGICAL_OR=14;
Blockly.PNP.ORDER_CONDITIONAL=15;Blockly.PNP.ORDER_LAMBDA=16;Blockly.PNP.ORDER_NONE=99;/*


 Copyright 2015 Erle Robotics
 http://erlerobotics.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
Blockly.PNP.pnp={};function rstrip_sc(a,b){return a.replace(/[\n ;]*$/g,"")}function pnpgen_action_string(a,b){var c=Blockly.PNP.valueToCode(b,"param",0),d=a;c&&(d=d+"_"+c);return d}Blockly.PNP.pnp_action=function(a){var b=a.getFieldValue("action");return pnpgen_action_string(b,a)+"; "};Blockly.PNP.pnp_condition=function(a){var b=a.getFieldValue("condition");return[pnpgen_action_string(b,a),0]};Blockly.PNP.pnp_comment=function(a){return"# "+a.getFieldValue("comment")+"\n"};
Blockly.PNP.pnp_er=function(a){return[a.getFieldValue("er"),0]};
Blockly.PNP.pnp_controls_if=function(a){var b=0,c=Blockly.PNP.valueToCode(a,"IF"+b,Blockly.PNP.ORDER_NONE)||"",d=Blockly.PNP.statementToCode(a,"DO"+b)||"";var e="\n< "+(c+"?"+rstrip_sc(d)+" ");for(b=1;b<=a.elseifCount_;b++)c=Blockly.PNP.valueToCode(a,"IF"+b,Blockly.PNP.ORDER_NONE)||"",d=Blockly.PNP.statementToCode(a,"DO"+b)||"",e+="\n  : "+c+"?"+rstrip_sc(d)+" ";a.elseCount_&&(d=Blockly.PNP.statementToCode(a,"ELSE")||"",e+="\n  : (NOT "+c+")?"+rstrip_sc(d)+" ");return rstrip_sc(e)+" \n>;\n"};Blockly.PNP.texts={};Blockly.PNP.text=function(a){return[Blockly.PNP.quote_(a.getFieldValue("TEXT")),Blockly.PNP.ORDER_ATOMIC]};Blockly.PNP.lists={};Blockly.PNP.lists_create_empty=function(a){return["",Blockly.PNP.ORDER_ATOMIC]};Blockly.PNP.lists_create_with=function(a){for(var b=Array(a.itemCount_),c=0;c<a.itemCount_;c++)b[c]=Blockly.PNP.valueToCode(a,"ADD"+c,Blockly.PNP.ORDER_NONE)||"None";b=b.join("_");return[b,Blockly.PNP.ORDER_ATOMIC]};